baseURL = "https://data-blog.gbif.org/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "GBIF Data Blog"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-even"

preserveTaxonomyNames = true
hasCJKLanguage = true     # has chinese/japanese/korean ? # 
paginate = 5                                              # 
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 

[author]                  # essential                     # 
  name = "olOwOlo"

[sitemap]                 # essential                     # 
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 
  name = "home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]             # config your menu              # 
  name = "authors"
  weight = 2
  identifier = "authors"
  url = "/authors/"
[[menu.main]]
  name = "tags"
  weight = 3
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "gbif.org"
  weight = 4
  identifier = "gbif"
  url = "https://www.gbif.org/"
[[menu.main]]
  name = "global-trends"
  weight = 5
  identifier = "analytics"
  url = "https://www.gbif.org/analytics/global"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[params]
  version = "3.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2017"            # Site creation time          # 

  # site info (optional)     
  logoSrc = "/logo.png" # the logo on the top of the page 
  gbifLogoSrc= "/GBIF-2015.png" # ignore unless you want to add gbif logo somewhere
  logoTitle = "GBIF Data Blog"        # default: the title value    # 
  keywords = ["Hugo", "theme","even"]
  description = "Hugo theme even example site."

  # paginate of archives, tags and categories             # 
  archivePaginate = 50

  # show 'xx Posts In Total' in archive page ?            # 
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 
  moreMeta = false

  # 
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            # 
  autoCollapseToc = false   # Auto expand and collapse toc                              # 
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 
  mathjax = false           # see https://www.mathjax.org/                              # 
  mathjaxEnableSingleDollar = false                                                     # 
  mathjaxEnableAutoNumber = false                                                       # 

  postMetaInFooter = true   # contain author, lastMod, markdown link, license           # 
  linkToMarkDown = false    # Only effective when hugo will output .md files.           # 
  contentCopyright = ''     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # 
  changyanAppkey = ""       # Changyan app key
  livereUID = ""            # LiveRe UID                  # 
  baidu_push = false        # baidu push                  # 
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # 

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ["/custom.css"]
  customJS = []

  [params.publicCDN]        # load these files from public cdn                          # 
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
    gitalkJS = '<script src="https://cdn.jsdelivr.net/npm/gitalk@1.2.2/dist/gitalk.min.js" integrity="sha256-DcjhdbufsHMHflFjZtKNFnPKOAL2ybOxGcPOR4MtnJg=" crossorigin="anonymous"></script>'
    gitalkCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1.2.2/dist/gitalk.css" integrity="sha256-rJVe5uyYRXdLM+Kkoj7JtN+9qI0bZTxkYTaNWODpg7U=" crossorigin="anonymous">'
    timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
    timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'

  # Display a message at the beginning of an article to warn the readers that it's content may be outdated.
  # 
  [params.outdatedInfoWarning]
    enable = false
    hint = 30               # Display hint if the last modified time is more than these days ago.    # 
    warn = 180              # Display warning if the last modified time is more than these days ago.    # 

  [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.flowchartDiagrams]# see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
    enable = false
    options = ""

  [params.sequenceDiagrams] # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
    enable = false
    options = ""            # default: "{theme: 'simple'}"

  [params.social]                                         # 
    a-github = "https://github.com/gbif"
    b-twitter = "https://twitter.com/GBIF?lang=en"
    c-instagram = "https://www.instagram.com/gbifs/?hl=en"
    d-vimeo = "https://github.com/gbif"
# 
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
